### ISSUE TITLE
could use a better documentation

### ISSUE THREAD

**Issue by xensor** [navarr/MinecraftProfile#6]
wow, how do you even install or set this up?

what files do i need to include?

what is needed?

you just show us how to call the commands, but not how to include the proper files or what to upload.

**Comment by navarr** [comment]
I'm very bad with documentation.  I'll update it to detail composer instructions.

Basically it uses composer.  A [Getting Started](https://getcomposer.org/doc/00-intro.md) is found at that link it's linked to.  Once you have composer setup and it's used in your project, you'd require `navarr/minecraft-profile` (typically `composer require navarr/minecraft-profile`) and then you'd ensure that you pull in vendor/autoload.php in order to setup the autoloader.

Then, you'd just follow the already shown how-to

**Comment by xensor** [comment]
thank you. that can make it easier to use. i know it uses composer. but sometimes it can be a pain to figure out what to use in composer to get it installed. i had some where u would type the name and it wouldn't work or be found.
